# Alternative of configMaps in order to send confidential data , incase of configMaps values are directly passed but in secrets values are decrypted in pods,no intervention in between ! 

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  ROOT_PASSWORD: dGVzdEAxMjM=  # Base64 encoded "test@123"